CREATE TABLE IF NOT EXISTS WALLETS (
    ID SERIAL PRIMARY KEY, FULL_NAME VARCHAR(100), DOCUMENT VARCHAR(100), EMAIL VARCHAR(100),
     "TYPE" INT, BALANCE DECIMAL(10, 2)
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON WALLETS (DOCUMENT);

CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON WALLETS (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID SERIAL PRIMARY KEY, PAYER INT, PAYEE INT, "VALUE" DECIMAL(10, 2), CREATED_AT TIMESTAMP,
    FOREIGN KEY (PAYER) REFERENCES WALLETS (ID), FOREIGN KEY (PAYEE) REFERENCES WALLETS (ID)
);